images_path: "../dataset/tiny_coco_images/"
labels_path: "../dataset/test/"
prediction_class: "../dataset/test/"
output_path: "../reports/"
Features:
  AspectRatio:
    visualization_methods: ["line"]
  ClassesFrequency:
    visualization_methods: [ "bar" ]
  InstancesPerImage:
    visualization_methods: ["boxplot"]
  LocationsMap:
    visualization_methods: [ ]



