images_path: "../dataset/train/images/"
labels_path: "../dataset/train/labels/"
masks_path: "../dataset/train/masks/"
predictions_path: "../dataset/train/predictions/"
output_path: "../reports/"

Features:
  AspectRatio:
    visualization_methods: ["scatter"]
  Color:
    visualization_methods: ["density"]
  Contrast:
    visualization_methods: ["density"]
  Brightness:
    visualization_methods: ["density"]

  ClassesFrequency:
    visualization_methods: ["bar"]
  InstancesPerImage:
    visualization_methods: ["boxplot"]

  LocationsMap:
    visualization_methods: []



