images_path: "../dataset/train/images/"
labels_path: "../dataset/train/labels/"
masks_path: "../dataset/train/masks/"
predictions_path: "../dataset/train/predictions/"
output_path: "../reports/"
Features:
  ClassesFrequency:
    visualization_methods: ["bar"]
  InstancesPerImage:
    visualization_methods: ["boxplot"]
  Precision:
    visualization_methods: ["boxplot"]
  LocationsMap:
    visualization_methods: []

