dataset_path: "../dataset/real_dataset/"
output_path: "../reports/"
Features:
  Color:
    visualization_methods: ["density"]
  Contrast:
    visualization_methods: [ "density" ]
  ChanelSplitAnalysis:
    visualization_methods: [ ]

  ClassesFrequency:
    visualization_methods: [ "bar" ]
  InstancesPerImage:
    visualization_methods: [ "density" ]
  LocationsMap:
    visualization_methods: [ ]


  ClassesAreaAnalysis:
    visualization_methods: ["boxplot"]
  ClassesBbAspectRatioAnalysis:
    visualization_methods: ["boxplot"]
  ClassesDiameterAnalysis:
    visualization_methods: ["boxplot"]
  Class2ImageRatioAnalysis:
    visualization_methods: ["boxplot"]


  MaskedContrastAnalysis:
    visualization_methods: [ "boxplot" ]
  MaskedBrightnessAnalysis:
    visualization_methods: [ "boxplot" ]
  MaskedGradientAnalysis:
    visualization_methods: [ "boxplot" ]


