dataset_path: "../dataset/real_dataset/"
output_path: "../reports/"
Features:
  ClassesSquareAnalysis:
    visualization_methods: [ "boxplot" ]
  Class2ImageRatioAnalysis:
    visualization_methods: [ "boxplot" ]


