dataset_path: "../dataset/real_dataset/"
output_path: "../reports/"
Features:
  AspectRatio:
    visualization_methods: [ "boxplot" ]
  Brightness:
    visualization_methods: [ "density" ]
  Color:
    visualization_methods: [ "density" ]
  Contrast:
    visualization_methods: [ "density" ]
  ClassesFrequency:
    visualization_methods: [ "bar" ]
  InstancesPerImage:
    visualization_methods: [ "density" ]
  LocationsMap:
    visualization_methods: [ ]
  ChanelSplitAnalysis:
    visualization_methods: [ ]

  ClassesSquareAnalysis:
    visualization_methods: [ "boxplot" ]
  Class2ImageRatioAnalysis:
    visualization_methods: [ "boxplot" ]
  ClassesBbAspectRatioAnalysis:
    visualization_methods: [ "boxplot" ]
  ClassesDiameterAnalysis:
    visualization_methods: [ "boxplot" ]


