dataset_path: "../dataset/real_dataset/"
output_path: "../reports/"
Features:
  Brightness:
    visualization_methods: [ "density" ]
  Color:
    visualization_methods: ["density"]
  Contrast:
    visualization_methods: [ "density" ]

  InstancesPerImage:
    visualization_methods: [ "density" ]



