dataset_path: "../dataset/real_dataset/"
output_path: "../reports/"
Features:
  Color:
    visualization_methods: [ "density" ]
  AspectRatio:
    visualization_methods: [ "scatter" ]
  Brightness:
    visualization_methods: [ "density" ]
  Contrast:
    visualization_methods: [ "density" ]
  ClassesFrequency:
    visualization_methods: [ "density" ]
  InstancesPerImage:
    visualization_methods: [ "density" ]
  LocationsMap:
    visualization_methods: [ ]
  ChanelSplitAnalysis:
    visualization_methods: [ ]
  ClassesDiameterAnalysis:
    visualization_methods: [ "boxplot" ]
  ClassesSquareAnalysis:
    visualization_methods: [ "boxplot" ]
