dataset_path: "../dataset/test_data/"
output_path: "../reports/"
Features:
  MaskedGradient:
    visualization_methods: [ "boxplot" ]
  MaskedContrast:
    visualization_methods: [ "boxplot", "histogram" ]
  MaskedBrightness:
    visualization_methods: [ "boxplot", "histogram" ]
